### ISSUE TITLE
Connect a USB cable from the navX-MXP circuit board to the RoboRIO to avoid brownouts

### ISSUE THREAD

**Issue by kushagharahi** [PearceRobotics/deep-space-2019#17]
2) Plan for RoboRIO Brownouts

The RoboRIO contains circuitry to remove power from the MXP connector when it detects an input voltage drop below a certain voltage level; this is known as a Stage 2 brownout. While brownouts do not typically occur during a FRC match (since fresh batteries are typically used at these times), during practice matches brownouts are common. If the robot drive chain draws large amounts of current, even for a short time, brownouts could potentially occur even with a FRC match.

navX-MXP maintains state information that will be reset when the navX-MXP circuit board is restarted. Avoiding navX-MXP restarts is very important if your robot software uses the “yaw” angle.

To avoid a navX-MXP restart when stage 2 brownouts occur, a secondary power supply for the navX-MXP circuit board should be provided. Fortunately, the RoboRIO provides just such a power supply, since its onboard USB interface is powered by a boost regulator which will provide 5V of power even when the RoboRIO input voltage (VIN) drops as low as 4.4 volts (once the RoboRIO VIN drops lower than this, the RoboRIO itself will restart).

To address this situation, simply connect a USB cable from the navX-MXP circuit board to the RoboRIO; if a brownout does occur, the navX-MXP circuit board will automatically switch to use power from the RoboRIO’s USB port.

**Comment by Stuart1745** [comment]
NavX Blew up issue no longer needed
